import SwiftUI
#if canImport(UIKit)
import UIKit
#endif
import LocationControlCore

public struct DiagnosticsView: View {
    @ObservedObject var appState: AppState

    public init(appState: AppState) {
        self.appState = appState
    }

    public var body: some View {
        NavigationStack {
            List {
                Section(header: Text("Environment Capabilities")) {
                    ForEach(appState.capabilityRegistry.capabilities) { cap in
                        VStack(alignment: .leading, spacing: 4) {
                            HStack {
                                Text(cap.name)
                                    .font(.subheadline)
                                    .bold()
                                Spacer()
                                StatusBadge(
                                    text: cap.isAvailable ? "Available" : "Restricted",
                                    isPositive: cap.isAvailable
                                )
                            }
                            Text(cap.detail)
                                .font(.caption)
                                .foregroundStyle(.secondary)
                            if let notes = cap.notes {
                                Text(notes)
                                    .font(.caption2)
                                    .foregroundStyle(.orange)
                            }
                        }
                        .padding(.vertical, 2)
                    }
                }

                Section(header: Text("Device & Platform Info")) {
                    #if canImport(UIKit)
                    LabeledContent("iOS Version", value: UIDevice.current.systemVersion)
                    LabeledContent("Device Model", value: UIDevice.current.model)
                    #else
                    LabeledContent("Platform", value: "macOS / Native")
                    #endif
                    LabeledContent("Protocol Version", value: "v\(CURRENT_PROTOCOL_VERSION)")
                    LabeledContent("Local Bridge", value: "Listening (ws://*:8765)")
                }

                Section(header: Text("Core Location Source Info")) {
                    Text("Apps reading `CLLocationSourceInformation.isSimulatedBySoftware` can observe when positions are generated by developer tooling.")
                        .font(.caption)
                        .foregroundStyle(.secondary)
                }
            }
            .navigationTitle("Diagnostics")
            .refreshable {
                appState.capabilityRegistry.refreshCapabilities()
            }
        }
    }
}
